### ISSUE TITLE
Plugins guardians - undefined variable

### ISSUE THREAD

**Issue by mchurchward** [vadimonus/moodle-local_purgequestioncategory#2]
With the plugin installed, if I access a non-quiz activity, I get an undefined variable warning thrown (with developer debugging on) as follows:
"Notice: Undefined variable: questionbank in /[moodleroot]/local/purgequestioncategory/lib.php on line 86"

**Comment by vadimonus** [comment]
Currently line 86 is empty. If you're using RC version from plugins repository, please checkout version from github, it contains some recently added fixes.

**Comment by mchurchward** [comment]
Hi Vadim -

I am checking the code for inclusion into the Moodle plugins database (https://moodle.org/plugins/local_purgequestioncategory). I am required to test the code that has been uploaded there. The issue exists in that code.
When you have new code that you are ready to upload, we will review that.

Thanks.

**Comment by vadimonus** [comment]
Hello again. As far, as plugins repository does not allows deletion of previous releases (only hide), i preffer not to upload all intermediate revisions there before your review and plugin publication. I've posted a lot of plugins into plugins repository last month (that's first), so when checking other m plugins please refer to latest github version. It will save me and you some time. I'll upload latest version as far as plugin is approved or if you just post me that github version is ok

**Comment by mchurchward** [comment]
Hi Vadim -
For this issue, I was able to easily verify that your latest code in github has fixed it. In general though, its best for you to fix all of the issues identified and then upload a new version for new testing.
Thanks.

**Comment by vadimonus** [comment]
Ready
