### ISSUE TITLE
Usability: Why do I have to select another category?

### ISSUE THREAD

**Issue by mudrd8mz** [vadimonus/moodle-local_purgequestioncategory#4]
Use case: I just imported dozens of questions by mistake. I have not added them to any quiz yet. When attempting to purge the imported category, I am forced to select another category to move questions to:
```
The category 'GCSE Computing categories' contains 141 questions (some of them may be old, hidden,
questions that are still in use in some existing quizzes). Please choose another category to move them
to.
```
This is confusing because I do not want to _move_ the questions. I want to delete them.

I understand that the tool can not delete used questions. But I would expect it detects such a need and asks for the target category only if needed.

**Comment by vadimonus** [comment]
I have taken core strings as prototype for this. I do not want to make this tool complex - it relies on library function for deleting. I do not want to have extra examination just to hide category selecctor. You will need to select checkbox anyway, so the form cannot be skiped.
Will you be satisfied of you see?
```
The category 'GCSE Computing categories' contains 141 questions (some of them may be old, hidden, questions that are still in use in some existing quizzes). Please choose another category to move them to **in case they cannot be deleted**.
```

**Comment by mudrd8mz** [comment]
Yes, it makes it clearer to me.

**Comment by vadimonus** [comment]
Fixed in last commit. Will not ask for category if categoriy does not contatin used questions
