### ISSUE TITLE
Usability: Better handle edge case when there is no question to be moved

### ISSUE THREAD

**Issue by mudrd8mz** [vadimonus/moodle-local_purgequestioncategory#6]
As @mchurchward noticed on the plugin page, when there is no question in the question banks, the UI does not give any hint to the user on what to do. It would be nice to display something like "There is no question to be purged" or so.

**Comment by vadimonus** [comment]
Oh you are all so hard... You make everything to make this the last plugin that i share with community. I made this plugin for necessity of my organisation. That is opensource, no paid support! If you want something, provide patch and i will integrate it.
But before you try to make such patch, just take a look. This plugin replicates the behaviour of core categories page. Why does core categroy page does not show you message "You cannot move this category up becase this is the first category"? The categories list is printed by very complex combination of list_item and moodle_list classes and it's children. It can show multiple categories in multiple contexts with pagination. To write something after some part of list (e.g. nothing to purge in this context) you need to rewrite moodle_list and question_category_list classes. This is twice a work of making this plugin.

**Comment by mchurchward** [comment]
Hi Vadim. 

I believe David opened this issue as a suggested improvement. Not as a requirement for acceptance. David has already approved and released your plugin to the community (https://moodle.org/plugins/local_purgequestioncategory). You may use the suggestion at your discretion. 
Part of the advantage of working in an Open Source development community is that you get the efforts of others to help you. Now that you have it out there, you may be able to find others who can help you improve it and possibly supply code.

**Comment by mudrd8mz** [comment]
Vadim, if you are not interested in well meant suggestions for improvements, why do you even bother and share your plugins? You could happily use them solely in your institution without being annoyed by any feedback.

You have submitted nice and well implemented plugins and I am happy for that. But let me clarify that it is _you_ asking for having these plugin hosted in the Plugins directory, with all the benefits and costs. Approving a plugin expects some commitments towards the Moodle community. The technical quality of the code is just one among several aspects of sharing things in an open source project.

Nobody forces you to work on these issues. I have dozens of open issues like this for my own projects as well, and surely there are many I will never ever fix in my life. That does not mean I have to be offensive to reporters.

And please, stop using arguments like "core does not do it too". There is nothing special about standard plugins that ship with Moodle. They are same contributions like yours, funded more or less by various institutions around the world. That has nothing to do with trying to simply implement the best code we can in the given time with given resources.

There was really no need for this counter-attack tone of your reply. There was no attack in the first place.
